name: deno-embeddings
services:
  db:
    image: pgvector/pgvector:pg16
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: unless-stopped
    env_file: ../.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

volumes:
  postgres_data:
